<?php

/**
 * Browser installer for WEDOS and similar shared hosting.
 *
 * This file is deliberately standalone because config/config.php does not exist
 * before the installer finishes. After installation it locks itself by detecting
 * the generated config file.
 */

$root = __DIR__;
$configTemplate = $root . '/config/config-template.php';
$configTarget = $root . '/config/config.php';
$schemaFile = $root . '/database/schema.sql';
$messages = [];
$errors = [];

/**
 * Escape HTML output.
 *
 * @param mixed $value Value to escape.
 * @return string Escaped value.
 */
function e(mixed $value): string
{
    return htmlspecialchars((string)$value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/**
 * Read a POST value with a default.
 *
 * @param string $key POST key.
 * @param string $default Default value.
 * @return string Trimmed value.
 */
function post_value(string $key, string $default = ''): string
{
    return trim((string)($_POST[$key] ?? $default));
}

/**
 * Generate a random application secret.
 *
 * @return string Hex encoded random bytes.
 */
function random_secret(): string
{
    return bin2hex(random_bytes(32));
}

if (is_file($configTarget)) {
    echo '<!doctype html><meta charset="utf-8"><title>Already installed</title>';
    echo '<style>body{font-family:system-ui;margin:3rem;max-width:760px}a{color:#f47b20}</style>';
    echo '<h1>Already installed</h1>';
    echo '<p><code>config/config.php</code> exists. Remove it only if you intentionally want to reinstall.</p>';
    echo '<p><a href="index.php">Open application</a></p>';
    exit;
}

$defaults = require $configTemplate;
$form = [
    'app_name' => post_value('app_name', $defaults['app']['name']),
    'base_url' => post_value('base_url', ''),
    'db_host' => post_value('db_host', $defaults['db']['host']),
    'db_port' => post_value('db_port', (string)$defaults['db']['port']),
    'db_name' => post_value('db_name', ''),
    'db_user' => post_value('db_user', ''),
    'db_password' => post_value('db_password', ''),
    'admin_username' => post_value('admin_username', 'admin'),
    'admin_email' => post_value('admin_email', ''),
    'admin_password' => post_value('admin_password', ''),
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    foreach (['app_name', 'db_host', 'db_port', 'db_name', 'db_user', 'admin_username', 'admin_email', 'admin_password'] as $required) {
        if ($form[$required] === '') {
            $errors[] = 'Missing required field: ' . $required;
        }
    }

    if (!filter_var($form['admin_email'], FILTER_VALIDATE_EMAIL)) {
        $errors[] = 'Admin e-mail is not valid.';
    }

    if (strlen($form['admin_password']) < 10) {
        $errors[] = 'Admin password must have at least 10 characters.';
    }

    if (!is_writable($root . '/config')) {
        $errors[] = 'The config directory is not writable by PHP.';
    }

    if (!$errors) {
        try {
            $dsn = sprintf(
                'mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',
                $form['db_host'],
                (int)$form['db_port'],
                $form['db_name']
            );
            $pdo = new PDO($dsn, $form['db_user'], $form['db_password'], [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ]);

            $schema = file_get_contents($schemaFile);
            if ($schema === false) {
                throw new RuntimeException('Could not read database/schema.sql.');
            }
            foreach (array_filter(array_map('trim', preg_split('/;\s*\n/', $schema) ?: [])) as $statement) {
                $pdo->exec($statement);
            }

            $pepper = random_secret();
            $passwordHash = password_hash($form['admin_password'] . $pepper, PASSWORD_DEFAULT);
            $stmt = $pdo->prepare(
                'INSERT INTO users (username, email, password_hash, role, created_at, updated_at) VALUES (?, ?, ?, ?, NOW(), NOW())'
            );
            $stmt->execute([$form['admin_username'], $form['admin_email'], $passwordHash, 'admin']);

            $config = $defaults;
            $config['app']['name'] = $form['app_name'];
            $config['app']['base_url'] = rtrim($form['base_url'], '/');
            $config['db']['host'] = $form['db_host'];
            $config['db']['port'] = (int)$form['db_port'];
            $config['db']['name'] = $form['db_name'];
            $config['db']['user'] = $form['db_user'];
            $config['db']['password'] = $form['db_password'];
            $config['security']['csrf_key'] = random_secret();
            $config['security']['password_pepper'] = $pepper;

            $content = "<?php\n\n/**\n * Generated by install.php. Do not commit this file.\n */\nreturn " . var_export($config, true) . ";\n";
            if (file_put_contents($configTarget, $content, LOCK_EX) === false) {
                throw new RuntimeException('Could not write config/config.php.');
            }

            header('Location: index.php?page=login&installed=1');
            exit;
        } catch (Throwable $exception) {
            $errors[] = $exception->getMessage();
        }
    }
}

?><!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Install Elite Bindings Vault</title>
    <style>
        :root { color-scheme: dark; --accent:#ff7a18; --bg:#091019; --panel:#101a26; --text:#eef4ff; --muted:#9fb2c7; }
        body { margin:0; font-family:system-ui,-apple-system,Segoe UI,sans-serif; background:radial-gradient(circle at top,#152338,#05080d 60%); color:var(--text); }
        main { max-width:900px; margin:0 auto; padding:40px 20px; }
        h1 { margin:0 0 8px; font-size:clamp(2rem,5vw,4rem); }
        p { color:var(--muted); }
        form { display:grid; gap:18px; background:rgba(16,26,38,.92); border:1px solid rgba(255,122,24,.25); border-radius:18px; padding:24px; box-shadow:0 18px 60px rgba(0,0,0,.35); }
        fieldset { border:1px solid rgba(255,255,255,.12); border-radius:14px; padding:18px; display:grid; gap:12px; }
        legend { color:var(--accent); padding:0 8px; }
        label { display:grid; gap:6px; font-weight:700; }
        input { background:#07101a; border:1px solid rgba(255,255,255,.18); color:var(--text); border-radius:10px; padding:12px 14px; font:inherit; }
        button { background:linear-gradient(135deg,#ff7a18,#ffb347); border:0; border-radius:999px; padding:14px 18px; font-weight:900; cursor:pointer; }
        .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(240px,1fr)); gap:12px; }
        .alert { padding:14px 16px; border-radius:12px; margin:12px 0; }
        .error { background:#3b1010; border:1px solid #bd3838; }
        code { color:#ffd49a; }
    </style>
</head>
<body>
<main>
    <h1>Install Elite Bindings Vault</h1>
    <p>This creates <code>config/config.php</code>, imports the MariaDB schema, and creates the first administrator.</p>

    <?php foreach ($errors as $error): ?>
        <div class="alert error"><?= e($error) ?></div>
    <?php endforeach; ?>

    <form method="post" autocomplete="off">
        <fieldset>
            <legend>Application</legend>
            <div class="grid">
                <label>Application name
                    <input name="app_name" value="<?= e($form['app_name']) ?>" required>
                </label>
                <label>Base URL, optional
                    <input name="base_url" value="<?= e($form['base_url']) ?>" placeholder="https://bindings.example.cz">
                </label>
            </div>
        </fieldset>
        <fieldset>
            <legend>MariaDB</legend>
            <div class="grid">
                <label>Host
                    <input name="db_host" value="<?= e($form['db_host']) ?>" required>
                </label>
                <label>Port
                    <input name="db_port" value="<?= e($form['db_port']) ?>" required>
                </label>
                <label>Database
                    <input name="db_name" value="<?= e($form['db_name']) ?>" required>
                </label>
                <label>User
                    <input name="db_user" value="<?= e($form['db_user']) ?>" required>
                </label>
                <label>Password
                    <input name="db_password" type="password" value="<?= e($form['db_password']) ?>">
                </label>
            </div>
        </fieldset>
        <fieldset>
            <legend>Administrator</legend>
            <div class="grid">
                <label>Username
                    <input name="admin_username" value="<?= e($form['admin_username']) ?>" required>
                </label>
                <label>E-mail
                    <input name="admin_email" type="email" value="<?= e($form['admin_email']) ?>" required>
                </label>
                <label>Password
                    <input name="admin_password" type="password" required minlength="10">
                </label>
            </div>
        </fieldset>
        <button type="submit">Install</button>
    </form>
</main>
</body>
</html>
